README.md
src/content-items/handler.ts
src/content-items/types.ts
src/content-items/utils.ts
src/directory/directory.ts
src/directory/handler.ts
src/file/file.ts
src/file/handler.ts
src/polyfills/Blob.js
test/integration/fdp-class.browser.spec.ts
test/integration/fdp-class.spec.ts
webpack.config.ts

feat: implemented delete file and delete directory features

---

src/index.ts

Exported fdp-contracts

---

README.md
package-lock.json
package.json
src/account/account-data.ts
src/account/account.ts
src/account/utils.ts
src/directory/directory.ts
src/feed/api.ts
src/file/file.ts
src/pod/api.ts
src/pod/personal-storage.ts
src/utils/wallet.ts
test/integration/fdp-class.browser.spec.ts
test/integration/fdp-class.spec.ts

Fixed interaction with seed

---

README.md
src/shim/crypto.ts

React native support added

---

test/integration/fdp-class.browser.spec.ts
test/integration/fdp-class.spec.ts

test: remove registrations where it is not needed

---

src/pod/utils.ts

The PR title got `fix` instead of `refactor` to trigger `release-please` CI action
Resolves: #138

fix: raise pod name limit

---

README.md
src/account/account-data.ts
src/account/utils.ts
test/integration/fdp-class.spec.ts

Implemented the ability to re-upload a portable account to SWARM
Close #142

feat: re-uploading a portable account to SWARM

---

README.md

Added workaround to prevent https://github.com/ethersphere/bee-js/issues/757
Close #110

docs: react native uploading data

---

README.md

docs: added setAccountFromMnemonic example

---

src/shim/crypto.ts

fix: crypto shim improved for next.js

---

README.md
src/pod/utils.ts

Close #16
Close #190 
Close #174

refactor: improved readme and pod type validation

---

src/directory/utils.ts
src/file/adapter.ts
src/file/handler.ts
src/file/utils.ts
src/pod/types.ts
src/pod/utils.ts
test/integration/fdp-class.fairos.spec.ts

Close https://github.com/fairDataSociety/fdp-storage/issues/206

feat: added permissions metadata for directories and files

---

package-lock.json
package.json
src/types.ts
test/utils.ts

fix: upgraded fdp-contracts-js lib

---

package-lock.json
package.json

feat: bee-js 6.2.0

---

src/pod/utils.ts
src/utils/type.ts
test/unit/pod/utils.spec.ts

Fixed bug when checking pod structure

fix: pod check structure improved

---

README.md
src/file/file.ts
src/file/handler.ts
src/file/types.ts
src/file/utils.ts
src/types.ts
src/utils/string.ts
src/utils/type.ts
test/integration/node/upload-by-index.spec.ts
test/utils.ts

Implemented uploading blocks of a file by index
https://github.com/fairDataSociety/fdp-storage/issues/265

feat: uploading blocks of a file by index

---

src/pod/utils.ts
src/utils/bytes.ts
test/integration/node/pod/pod-limit-error-message.spec.ts

Close: https://github.com/fairDataSociety/fdp-storage/issues/260

fix: add length assertion for pod list size

---

src/types.ts

feat: export length constants for pod and directory names

---

src/types.ts

Close https://github.com/fairDataSociety/fdp-storage/issues/168

feat: export PodTypes, Encryption, and Bytes

---

src/account/account-data.ts
src/account/types.ts
src/account/utils.ts
src/directory/directory.ts
src/file/file.ts
src/pod/personal-storage.ts
src/utils/string.ts
test/integration/node/batch-id/batch-id-only-for-write.spec.ts
test/utils.ts

Close: https://github.com/fairDataSociety/fdp-storage/issues/201

feat: clear postage batch error

---

.eslintrc.js
tsconfig.test.json

Close https://github.com/fairDataSociety/fdp-storage/issues/172

feat: enforce await-thenable eslint rule and update tsconfig.test.json

---

package-lock.json
package.json

fdp-contract upgraded to 3.10.0

feat: fdp-contract 3.10.0
